// react
import { useEffect, useState } from "react";

// next
import Head from "next/head";

// styles
import style from "../styles/MainCard.module.scss";

// types
import { CardsResponse, CartStore } from "../types";

// components
import MainCard from "../components/index/MainCard";
import Card from "../components/index/Card";

// services
import { useAllProducts } from "../services/useAllProducts";

export default function Home() {
  const [cart, setCart] = useState<CartStore[]>([]);

  const { isLoading, allProducts: products } = useAllProducts();

  if (isLoading) {
    return <>Loading....</>;
  }

  function setFavourites(cardId: number, favourites: boolean) {
    const filteredCart = cart.map((el) => {
      if (el.id === cardId) {
        el.isFavourites = favourites;
      }

      return el;
    });

    setCart(filteredCart);
  }

  function updateCart(newCart: CartStore[]) {
    console.log(1);
    setCart(newCart);
  }

  return (
    <>
      <Head>
        <title>Socket Ball</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
      <main className={style.main}>
        <MainCard />
        <>
          {products &&
            products.map((elem: CardsResponse) => (
              <Card
                el={elem}
                cart={cart}
                updateCart={updateCart}
                setFavourites={setFavourites}
                key={elem.id}
              />
            ))}
        </>
      </main>
    </>
  );
}
